### PR TITLE
Don't check the links in draft docs

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

@dnephin @moxiegirl

### CODE REVIEW

**Comment by SvenDowideit** [comment]
replacement for https://github.com/docker/markdownlint/pull/8

**Comment by SvenDowideit** [comment]
@dnephin - does this look resonable to you?

**Comment by dnephin** [comment]
LGTM

**Comment by moxiegirl** [comment]
OK. I'll not test this...I'll look what happens in the build an kibitz there

**Pull request merged**
